version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-coroutines-reactor"
        versions: ["1.6.0-RC2", "1.6.0-RC3", "1.6.0"]
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-coroutines-core"
        versions: ["1.6.0-RC2", "1.6.0-RC3", "1.6.0"]
      - dependency-name: "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm"
        versions: ["1.6.0-RC2", "1.6.0-RC3", "1.6.0"]
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
          - "kotlin*"
          - "*kotlin*"
      spring:
        patterns:
          - "*spring*"
      junit-jupiter:
        patterns:
          - "junit*"
          - "*junit*"
          - "*junit*"
          - "*jupiter"
          - "jupiter*"
          - "*jupiter*"

  - package-ecosystem: npm
    directory: "/jofisaes-image-morpher-js"
    schedule:
      interval: "daily"
