name: Image Sizer PR
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test
        run: mvn clean install

      - name: Maven OWASP Security Check
        run: mvn clean install -Powasp
